version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flexy_booker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://host.docker.internal:5432/flexy-booker -user=postgres -password=13752113 migrate
    volumes:
      - ./src/db/migration:/flyway/sql

volumes:
  postgres_data: