#!/bin/sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --no-use
[ -s "$NVM_DIR/alias/default" ] && nvm use default --silent 2>/dev/null || true

./node_modules/.bin/commitlint --edit "$1"
